import { randomUUID } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import express, { type NextFunction, type Request, type Response } from "express";
import cors from "cors";
import helmet from "helmet";
import { z } from "zod";
import type { AuthenticationResponseJSON, RegistrationResponseJSON } from "@simplewebauthn/server";
import { API_KEY_SCOPES, BROWSER_SCOPES, BrowserOperatorActionSchema, CreateIntentInputSchema, CreateShoppingTaskInputSchema, CreateWebPurchaseTaskInputSchema, MCP_SCOPES, PaymentPreferenceSchema, RedactedPageSnapshotSchema, sha256 } from "@spendseal/core";
import type { Config } from "./config.js";
import { handleMcpRequest } from "./mcp.js";
import { OAuthService } from "./oauth.js";
import { verifyWebhookSignature } from "./payments.js";
import { SpendSealError, SpendSealService } from "./service.js";
import { SpendSealStore, type SessionPrincipal } from "./store.js";
import { SpendSealWebAuthn } from "./webauthn.js";
import { seedNovaDesk } from "./demo.js";
import { BrowserAgentService, type BrowserPrincipal } from "./browser-agent.js";

export function createApp(config: Config, store: SpendSealStore) {
  const service = new SpendSealService(store, config); const browserAgent = new BrowserAgentService(store.pool, config.browserLivePurchaseEnabled, config.browserAgentEnabled, config.browserLiveBuyerIds, config.openAiCreditsLiveEnabled, config.genericWebLiveEnabled); const webauthn = new SpendSealWebAuthn(store, config, browserAgent); const oauth = new OAuthService(store, config); const app = express();
  app.disable("x-powered-by"); app.set("trust proxy", 1);
  app.use((req, res, next) => { const id = String(req.header("x-request-id") ?? randomUUID()); res.setHeader("x-request-id", id); res.locals.requestId = id; const started = Date.now(); res.on("finish", () => console.log(JSON.stringify({ level: "info", event: "http_request", requestId: id, method: req.method, path: req.path, status: res.statusCode, durationMs: Date.now() - started }))); next(); });
  app.use(helmet({ contentSecurityPolicy: false, crossOriginEmbedderPolicy: false }));
  app.use(cors({ origin(origin, callback) { callback(null, !origin || origin === config.webauthnOrigin || origin.startsWith("chrome-extension://")); }, credentials: true, methods: ["GET", "POST", "PATCH", "PUT", "DELETE"] }));

  app.post("/api/webhooks/razorpay/:merchantId", express.raw({ type: "application/json", limit: "256kb" }), asyncHandler(async (req, res) => {
    const merchantId = z.string().uuid().parse(req.params.merchantId); const paymentConfig = await store.paymentConfig(merchantId);
    if (!paymentConfig?.webhookSecretCiphertext) throw new SpendSealError(404, "PAYMENT_CONFIG_MISSING", "Merchant webhook configuration was not found.");
    const rawBody = req.body as Buffer; const signature = String(req.header("x-razorpay-signature") ?? "");
    if (!verifyWebhookSignature(rawBody, signature, service.vault.decrypt(paymentConfig.webhookSecretCiphertext))) throw new SpendSealError(400, "INVALID_WEBHOOK_SIGNATURE", "Webhook signature verification failed.");
    const body = JSON.parse(rawBody.toString("utf8")) as { event?: string; payload?: { payment?: { entity?: { id?: string; order_id?: string } } } }; const eventId = String(req.header("x-razorpay-event-id") ?? "");
    if (!eventId || !await store.recordWebhook(merchantId, eventId, body.event ?? "unknown")) { res.json({ ok: true, duplicate: true }); return; }
    const providerOrderId = body.payload?.payment?.entity?.order_id; const paymentId = body.payload?.payment?.entity?.id;
    if (body.event === "payment.captured" && providerOrderId && paymentId) { const order = await store.getOrderByProvider(merchantId, providerOrderId); if (order && order.status !== "paid") await store.markPaid(order.id, paymentId, "razorpay"); }
    res.json({ ok: true, duplicate: false });
  }));

  app.use(express.json({ limit: "256kb" }));
  app.use((req, res, next) => { void attachSession(req, res, store, config).then(() => next(), next); });

  app.get("/api/v1/health", asyncHandler(async (_req, res) => { await store.health(); res.json({ ok: true, database: "postgresql", migrations: "ready", mode: config.demoMode ? "demo" : "standard" }); }));

  app.post("/api/v1/auth/passkeys/register/options", limit(store, "register", 10, 300), asyncHandler(async (req, res) => {
    const input = z.object({
      username: z.string().trim().min(3).max(120).regex(/^[a-zA-Z0-9@._+-]+$/),
      displayName: z.string().trim().min(1).max(120),
    }).parse(req.body);
    res.json(await webauthn.registrationOptions(input.username, input.displayName));
  }));
  app.post("/api/v1/auth/passkeys/register/verify", limit(store, "register_verify", 10, 300), asyncHandler(async (req, res) => {
    const input = z.object({ challengeId: z.string().uuid(), response: z.unknown() }).parse(req.body); const verified = await webauthn.verifyRegistration(input.challengeId, input.response as RegistrationResponseJSON); const session = await store.createSession(verified.user.id, config.sessionIdleMinutes, config.sessionAbsoluteHours); setSession(res, session, config); res.status(201).json({ user: verified.user, csrfToken: session.csrf });
  }));
  app.post("/api/v1/auth/passkeys/login/options", limit(store, "login", 12, 300), asyncHandler(async (req, res) => { const input = z.object({ username: z.string().trim().min(3).max(120) }).parse(req.body); res.json(await webauthn.loginOptions(input.username)); }));
  app.post("/api/v1/auth/passkeys/login/verify", limit(store, "login_verify", 12, 300), asyncHandler(async (req, res) => {
    const input = z.object({ challengeId: z.string().uuid(), response: z.unknown() }).parse(req.body); const verified = await webauthn.verifyLogin(input.challengeId, input.response as AuthenticationResponseJSON); const session = await store.createSession(verified.user.id, config.sessionIdleMinutes, config.sessionAbsoluteHours); setSession(res, session, config); res.json({ user: verified.user, csrfToken: session.csrf });
  }));
  app.get("/api/v1/auth/session", requireBrowser, (req, res) => res.json({ user: principal(res).user, csrfToken: cookie(req, "agentrail_csrf") }));
  app.post("/api/v1/auth/logout", requireBrowser, requireCsrf, asyncHandler(async (req, res) => { const token = cookie(req, "agentrail_session"); if (token) await store.deleteSession(token); clearSession(res); res.json({ ok: true }); }));

  app.get("/api/v1/merchants", requireBrowser, asyncHandler(async (_req, res) => res.json(await store.listMerchants({ userId: principal(res).user.id }))));
  app.get("/api/v1/catalog/merchants", requireBrowser, asyncHandler(async (req, res) => res.json(await store.listMerchants({ query: stringQuery(req.query.q), cursor: stringQuery(req.query.cursor) }))));
  app.post("/api/v1/merchants", requireBrowser, requireCsrf, limit(store, "merchant_create", 10, 3600), asyncHandler(async (req, res) => {
    const input = z.object({ slug: z.string().min(2).max(60).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), displayName: z.string().min(1).max(120) }).parse(req.body); res.status(201).json({ merchant: await store.createMerchant(principal(res).user.id, input) });
  }));
  app.get("/api/v1/merchants/:merchantId/members", requireBrowser, asyncHandler(async (req, res) => { const merchantId = uuidParam(req.params.merchantId); await requireMembership(store, principal(res).user.id, merchantId, ["owner", "admin"]); res.json({ members: await store.listMemberships(merchantId), invitations: await store.listInvitations(merchantId) }); }));
  app.post("/api/v1/merchants/:merchantId/invitations", requireBrowser, requireCsrf, limit(store, "membership_invite", 30, 3600), asyncHandler(async (req, res) => { const merchantId = uuidParam(req.params.merchantId); await requireMembership(store, principal(res).user.id, merchantId, ["owner", "admin"]); const input = z.object({ username: z.string().min(3).max(120), role: z.enum(["admin", "catalog_manager", "auditor"]) }).parse(req.body); res.status(201).json(await store.createInvitation(merchantId, principal(res).user.id, input.username, input.role)); }));
  app.post("/api/v1/invitations/accept", requireBrowser, requireCsrf, asyncHandler(async (req, res) => { const token = z.object({ token: z.string().min(20) }).parse(req.body).token; const result = await store.acceptInvitation(principal(res).user, token); if (!result) throw new SpendSealError(404, "INVITATION_INVALID", "The invitation is invalid, expired, or intended for a different username."); res.json(result); }));
  app.patch("/api/v1/merchants/:merchantId/members/:userId", requireBrowser, requireCsrf, asyncHandler(async (req, res) => { const merchantId = uuidParam(req.params.merchantId); const actor = principal(res).user.id; await requireMembership(store, actor, merchantId, ["owner"]); const role = z.object({ role: z.enum(["owner", "admin", "catalog_manager", "auditor"]) }).parse(req.body).role; try { const updated = await store.updateMembershipRole(merchantId, actor, uuidParam(req.params.userId), role); if (!updated) throw new SpendSealError(404, "MEMBERSHIP_NOT_FOUND", "Membership not found."); res.json({ updated: true }); } catch (error) { if (error instanceof Error && error.message === "LAST_OWNER") throw new SpendSealError(409, "LAST_OWNER", "A merchant must retain at least one owner."); throw error; } }));

  app.get("/api/v1/merchants/:merchantId/catalog-connection", requireBrowser, asyncHandler(async (req, res) => { const merchantId = uuidParam(req.params.merchantId); await requireMembership(store, principal(res).user.id, merchantId, ["owner", "admin", "catalog_manager", "auditor"]); const value = await store.catalogConnection(merchantId); res.json({ connection: value ? { provider: value.provider, shopDomain: value.shopDomain, shopName: value.shopName, currency: value.currency, status: value.status, defaultRefundable: value.defaultRefundable, defaultRefundWindowDays: value.defaultRefundWindowDays, lastSyncAt: value.lastSyncAt, connected: true } : null }); }));
  app.put("/api/v1/merchants/:merchantId/catalog-connection/shopify", requireBrowser, requireCsrf, limit(store, "shopify_connect", 10, 3600), asyncHandler(async (req, res) => { const merchantId = uuidParam(req.params.merchantId); await requireMembership(store, principal(res).user.id, merchantId, ["owner"]); const input = z.object({ shopDomain: z.string().min(1).max(255), accessToken: z.string().min(16).max(512), defaultRefundable: z.boolean().default(false), defaultRefundWindowDays: z.number().int().min(0).max(365).default(0) }).parse(req.body); res.json(await service.configureShopify(merchantId, principal(res).user.id, input)); }));
  app.post("/api/v1/merchants/:merchantId/catalog-connection/shopify/sync", requireBrowser, requireCsrf, limit(store, "shopify_sync", 30, 3600), asyncHandler(async (req, res) => { const merchantId = uuidParam(req.params.merchantId); await requireMembership(store, principal(res).user.id, merchantId, ["owner", "admin", "catalog_manager"]); res.json({ sync: await service.syncShopify(merchantId, principal(res).user.id) }); }));

  app.get("/api/v1/merchants/:merchantId/products", requireBrowserOrApiKey(store, "catalog:read"), asyncHandler(async (req, res) => { const merchantId = uuidParam(req.params.merchantId); await requireMerchantAccess(res, store, merchantId, ["owner", "admin", "catalog_manager", "auditor"]); res.json(await store.listProducts(merchantId, stringQuery(req.query.q), numberQuery(req.query.limit) ?? 50, stringQuery(req.query.cursor), req.query.includeArchived === "true")); }));
  app.get("/api/v1/catalog/merchants/:merchantId/products", requireBrowser, asyncHandler(async (req, res) => res.json(await store.listProducts(uuidParam(req.params.merchantId), stringQuery(req.query.q), 50, stringQuery(req.query.cursor)))));
  app.post("/api/v1/merchants/:merchantId/products", requireBrowserOrApiKey(store, "catalog:write"), requireCsrfIfBrowser, limit(store, "catalog_write", 120, 60), asyncHandler(async (req, res) => {
    const merchantId = uuidParam(req.params.merchantId); await requireMerchantAccess(res, store, merchantId, ["owner", "admin", "catalog_manager"]); const input = productInput().parse(req.body); const actorId = principalOptional(res)?.user.id ?? z.string().uuid().parse(res.locals.apiUserId ?? principalOptional(res)?.user.id ?? await ownerId(store, merchantId)); res.status(201).json({ product: await store.createProduct(actorId, merchantId, input) });
  }));
  app.patch("/api/v1/merchants/:merchantId/products/:productId", requireBrowserOrApiKey(store, "catalog:write"), requireCsrfIfBrowser, limit(store, "catalog_write", 120, 60), asyncHandler(async (req, res) => {
    const merchantId = uuidParam(req.params.merchantId); await requireMerchantAccess(res, store, merchantId, ["owner", "admin", "catalog_manager"]); const input = productUpdateInput().parse(req.body); const actorId = principalOptional(res)?.user.id ?? await ownerId(store, merchantId); let product; try { product = await store.updateProduct(actorId, merchantId, uuidParam(req.params.productId), input.expectedVersion, input.changes); } catch (error) { if (error instanceof Error && error.message === "EXTERNAL_SOURCE") throw new SpendSealError(409, "SHOPIFY_PRODUCT_READ_ONLY", "Change this product in Shopify, then synchronize the authoritative catalog."); throw error; } if (product === "VERSION_CONFLICT") throw new SpendSealError(409, "PRODUCT_VERSION_CONFLICT", "The product changed after this edit was loaded."); if (!product) throw new SpendSealError(404, "PRODUCT_NOT_FOUND", "Product not found."); res.json({ product });
  }));
  app.get("/api/v1/merchants/:merchantId/products/:productId/revisions", requireBrowserOrApiKey(store, "catalog:read"), asyncHandler(async (req, res) => { const merchantId = uuidParam(req.params.merchantId); await requireMerchantAccess(res, store, merchantId, ["owner", "admin", "catalog_manager", "auditor"]); res.json({ revisions: await store.productRevisions(merchantId, uuidParam(req.params.productId)) }); }));

  app.get("/api/v1/merchants/:merchantId/api-keys", requireBrowser, asyncHandler(async (req, res) => { const merchantId = uuidParam(req.params.merchantId); await requireMembership(store, principal(res).user.id, merchantId, ["owner", "admin"]); res.json({ apiKeys: await store.listApiKeys(merchantId) }); }));
  app.post("/api/v1/merchants/:merchantId/api-keys", requireBrowser, requireCsrf, asyncHandler(async (req, res) => { const merchantId = uuidParam(req.params.merchantId); await requireMembership(store, principal(res).user.id, merchantId, ["owner", "admin"]); const input = z.object({ name: z.string().min(1).max(80), scopes: z.array(z.enum(API_KEY_SCOPES)).min(1), expiresAt: z.string().datetime().nullable().default(null) }).parse(req.body); res.status(201).json(await store.createApiKey(merchantId, input.name, input.scopes, input.expiresAt)); }));
  app.delete("/api/v1/merchants/:merchantId/api-keys/:id", requireBrowser, requireCsrf, asyncHandler(async (req, res) => { const merchantId = uuidParam(req.params.merchantId); await requireMembership(store, principal(res).user.id, merchantId, ["owner", "admin"]); res.json({ revoked: await store.revokeApiKey(merchantId, uuidParam(req.params.id)) }); }));
  app.post("/api/v1/merchants/:merchantId/api-keys/:id/rotate", requireBrowser, requireCsrf, asyncHandler(async (req, res) => { const merchantId = uuidParam(req.params.merchantId); await requireMembership(store, principal(res).user.id, merchantId, ["owner", "admin"]); const replacement = await store.rotateApiKey(merchantId, uuidParam(req.params.id)); if (!replacement) throw new SpendSealError(404, "API_KEY_NOT_FOUND", "Active API key not found."); res.status(201).json(replacement); }));
  app.get("/api/v1/merchants/:merchantId/orders", requireBrowserOrApiKey(store, "orders:read"), asyncHandler(async (req, res) => { const merchantId = uuidParam(req.params.merchantId); await requireMerchantAccess(res, store, merchantId, ["owner", "admin", "auditor"]); res.json({ orders: await store.listMerchantOrders(merchantId) }); }));
  app.get("/api/v1/merchants/:merchantId/audit", requireBrowserOrApiKey(store, "audit:read"), asyncHandler(async (req, res) => { const merchantId = uuidParam(req.params.merchantId); await requireMerchantAccess(res, store, merchantId, ["owner", "admin", "auditor"]); res.json({ events: await store.auditTrail("merchant", merchantId), verification: await store.verifyAudit("merchant", merchantId) }); }));

  app.get("/api/v1/merchants/:merchantId/payment-configuration", requireBrowser, asyncHandler(async (req, res) => { const merchantId = uuidParam(req.params.merchantId); await requireMembership(store, principal(res).user.id, merchantId, ["owner", "admin"]); const value = await store.paymentConfig(merchantId); res.json({ configuration: value ? { adapter: value.adapter, keyId: value.keyId, version: value.version, connected: true, webhookUrl: `${config.publicBaseUrl}/api/webhooks/razorpay/${merchantId}` } : null, localImportAvailable: Boolean(config.localRazorpayKeyId && config.localRazorpayKeySecret) }); }));
  app.put("/api/v1/merchants/:merchantId/payment-configuration", requireBrowser, requireCsrf, asyncHandler(async (req, res) => { const merchantId = uuidParam(req.params.merchantId); await requireMembership(store, principal(res).user.id, merchantId, ["owner"]); const input = z.discriminatedUnion("adapter", [z.object({ adapter: z.literal("mock") }), z.object({ adapter: z.literal("razorpay"), keyId: z.string().startsWith("rzp_test_"), keySecret: z.string().min(8) })]).parse(req.body); res.json(await service.configurePayments(merchantId, input)); }));
  app.post("/api/v1/merchants/:merchantId/payment-configuration/import-local-test-keys", requireBrowser, requireCsrf, limit(store, "razorpay_import", 5, 3600), asyncHandler(async (req, res) => { const merchantId = uuidParam(req.params.merchantId); await requireMembership(store, principal(res).user.id, merchantId, ["owner"]); if (!config.localRazorpayKeyId || !config.localRazorpayKeySecret) throw new SpendSealError(404, "LOCAL_TEST_KEYS_MISSING", "Razorpay Test keys are not configured in the local server environment."); res.json(await service.configurePayments(merchantId, { adapter: "razorpay", keyId: config.localRazorpayKeyId, keySecret: config.localRazorpayKeySecret })); }));
  app.post("/api/v1/merchants/:merchantId/payment-configuration/webhook-secret/rotate", requireBrowser, requireCsrf, limit(store, "razorpay_webhook_secret_rotate", 3, 3600), asyncHandler(async (req, res) => { const merchantId = uuidParam(req.params.merchantId); await requireMembership(store, principal(res).user.id, merchantId, ["owner"]); res.status(201).json(await service.rotateRazorpayWebhookSecret(merchantId)); }));

  app.post("/api/v1/demo/seed", requireBrowser, requireCsrf, asyncHandler(async (_req, res) => { if (!config.demoMode) throw new SpendSealError(404, "NOT_AVAILABLE", "Optional demo seeding is disabled."); res.status(201).json(await seedNovaDesk(store, service, principal(res).user.id)); }));

  app.get("/api/v1/intents", requireBrowser, asyncHandler(async (_req, res) => res.json({ intents: await store.listBuyerIntents(principal(res).user.id) })));
  app.post("/api/v1/intents", requireBrowser, requireCsrf, limit(store, "intent_create", 30, 60), asyncHandler(async (req, res) => res.status(201).json(await service.createIntent(principal(res).user.id, CreateIntentInputSchema.parse(req.body), "buyer"))));
  app.get("/api/v1/intents/:id", requireBrowser, asyncHandler(async (req, res) => { const intent = await store.getIntent(uuidParam(req.params.id), principal(res).user.id); if (!intent) throw new SpendSealError(404, "INTENT_NOT_FOUND", "PurchasePermit not found for this buyer."); const product = await store.getProduct(intent.merchantId, intent.productId); res.json({ intent, product }); }));
  app.post("/api/v1/intents/:id/approval-session", requireBrowser, requireCsrf, asyncHandler(async (req, res) => { const id = uuidParam(req.params.id); const token = z.object({ token: z.string().min(1) }).parse(req.body).token; const session = await store.exchangeApprovalToken(id, principal(res).user.id, token); if (!session) throw new SpendSealError(403, "INVALID_APPROVAL_LINK", "This link is invalid, expired, already exchanged, or belongs to another buyer."); res.cookie(approvalCookieName(id), session.token, { httpOnly: true, secure: config.webauthnOrigin.startsWith("https://"), sameSite: "strict", expires: new Date(session.expiresAt), path: `/api/v1/intents/${id}` }); res.json({ expiresAt: session.expiresAt }); }));
  app.post("/api/v1/intents/:id/approval/options", requireBrowser, requireCsrf, asyncHandler(async (req, res) => res.json(await webauthn.approvalOptions(uuidParam(req.params.id), principal(res).user.id, requireApprovalCookie(req)))));
  app.post("/api/v1/intents/:id/approve", requireBrowser, requireCsrf, asyncHandler(async (req, res) => { const id = uuidParam(req.params.id); const input = z.object({ challengeId: z.string().uuid(), response: z.unknown() }).parse(req.body); const intent = await webauthn.approve(id, principal(res).user.id, requireApprovalCookie(req), input.challengeId, input.response as AuthenticationResponseJSON); res.clearCookie(approvalCookieName(id), { path: `/api/v1/intents/${id}` }); res.json({ intent, approvalMethod: "passkey" }); }));
  app.post("/api/v1/intents/:id/checkout", requireBrowser, requireCsrf, limit(store, "checkout", 20, 60), asyncHandler(async (req, res) => res.json(await service.prepareCheckout(principal(res).user.id, uuidParam(req.params.id)))));
  app.get("/api/v1/intents/:id/audit", requireBrowser, asyncHandler(async (req, res) => { const id = uuidParam(req.params.id); if (!await store.getIntent(id, principal(res).user.id)) throw new SpendSealError(404, "INTENT_NOT_FOUND", "PurchasePermit not found for this buyer."); res.json({ events: await store.auditTrail("intent", id), verification: await store.verifyAudit("intent", id) }); }));

  app.get("/api/v1/checkout/:token", requireBrowser, asyncHandler(async (req, res) => { const details = await service.checkoutDetails(String(req.params.token)); if (details.intent.buyerId !== principal(res).user.id) throw new SpendSealError(403, "TENANT_ACCESS_DENIED", "Checkout belongs to another buyer."); res.json(details); }));
  app.post("/api/v1/payments/verify", requireBrowser, requireCsrf, asyncHandler(async (req, res) => { const input = z.object({ localOrderId: z.string().uuid(), razorpayOrderId: z.string(), razorpayPaymentId: z.string(), razorpaySignature: z.string() }).parse(req.body); const order = await store.getOrder(input.localOrderId); if (!order || order.buyerId !== principal(res).user.id) throw new SpendSealError(403, "TENANT_ACCESS_DENIED", "Payment belongs to another buyer."); res.json({ order: await service.verifyPayment(input) }); }));
  app.post("/api/v1/payments/mock-complete", requireBrowser, requireCsrf, asyncHandler(async (req, res) => { const id = z.object({ localOrderId: z.string().uuid() }).parse(req.body).localOrderId; const order = await store.getOrder(id); if (!order || order.buyerId !== principal(res).user.id) throw new SpendSealError(403, "TENANT_ACCESS_DENIED", "Payment belongs to another buyer."); res.json({ order: await service.completeMockPayment(id) }); }));

  app.get("/api/v1/shopping-tasks", requireBrowser, asyncHandler(async (_req, res) => res.json({ tasks: await browserAgent.listTasks(principal(res).user.id) })));
  app.post("/api/v1/shopping-tasks", requireBrowser, requireCsrf, limit(store, "shopping_create", 30, 60), asyncHandler(async (req, res) => res.status(201).json({ task: await browserAgent.createTask(principal(res).user.id, CreateShoppingTaskInputSchema.parse(req.body)) })));
  app.post("/api/v1/web-purchase-tasks", requireBrowser, requireCsrf, limit(store, "shopping_create", 30, 60), asyncHandler(async (req, res) => res.status(201).json({ task: await browserAgent.createWebTask(principal(res).user.id, CreateWebPurchaseTaskInputSchema.parse(req.body)) })));
  app.get("/api/v1/shopping-tasks/:id", requireBrowser, asyncHandler(async (req, res) => res.json(await browserAgent.getTask(uuidParam(req.params.id), principal(res).user.id))));
  app.get("/api/v1/shopping-tasks/:id/audit", requireBrowser, asyncHandler(async (req, res) => res.json(await browserAgent.audit(uuidParam(req.params.id), principal(res).user.id))));
  app.post("/api/v1/shopping-tasks/:id/approval/options", requireBrowser, requireCsrf, asyncHandler(async (req, res) => res.json(await webauthn.shoppingApprovalOptions(uuidParam(req.params.id), principal(res).user.id))));
  app.post("/api/v1/shopping-tasks/:id/approve", requireBrowser, requireCsrf, asyncHandler(async (req, res) => { const input = z.object({ challengeId: z.string().uuid(), response: z.unknown() }).parse(req.body); res.json({ task: await webauthn.approveShoppingTask(uuidParam(req.params.id), principal(res).user.id, input.challengeId, input.response as AuthenticationResponseJSON), approvalMethod: "passkey" }); }));
  app.post("/api/v1/shopping-tasks/:id/approval-continuations/:continuationId/complete", requireBrowser, requireCsrf, asyncHandler(async (req, res) => res.json(await browserAgent.completeApprovalContinuation(uuidParam(req.params.id), principal(res).user.id, uuidParam(req.params.continuationId)))));

  app.post("/api/v1/browser/installations", limit(store, "browser_installation", 20, 60), asyncHandler(async (req, res) => { const extension = await requireExtensionPrincipal(req, oauth, "browser:tasks:read"); const input = z.object({ installationId: z.string().uuid(), name: z.string().min(1).max(80) }).parse(req.body); await browserAgent.registerInstallation(extension, input); res.status(201).json({ registered: true, livePurchaseEnabled: browserAgent.liveModeEnabledFor(extension.userId) }); }));
  app.delete("/api/v1/browser/installations/:id", limit(store, "browser_installation", 20, 60), asyncHandler(async (req, res) => { const extension = await requireExtensionPrincipal(req, oauth, "browser:tasks:read"); res.json({ revoked: await browserAgent.revokeInstallation(extension.userId, uuidParam(req.params.id)) }); }));
  app.get("/api/v1/browser/tasks/pending", limit(store, "browser_read", 120, 60), asyncHandler(async (req, res) => { const extension = await requireExtensionPrincipal(req, oauth, "browser:tasks:read"); res.json({ tasks: await browserAgent.listTasks(extension.userId, true) }); }));
  app.get("/api/v1/browser/tasks/:id", limit(store, "browser_read", 120, 60), asyncHandler(async (req, res) => { const extension = await requireExtensionPrincipal(req, oauth, "browser:tasks:read"); res.json(await browserAgent.getTask(uuidParam(req.params.id), extension.userId)); }));
  app.get("/api/v1/browser/tasks/:id/fx-quote", limit(store, "browser_read", 30, 60), asyncHandler(async (req, res) => { const extension = await requireExtensionPrincipal(req, oauth, "browser:tasks:read"); res.json({ fxQuote: await browserAgent.fxQuote(uuidParam(req.params.id), extension.userId) }); }));
  app.post("/api/v1/browser/tasks/:id/candidates", limit(store, "browser_observation", 120, 60), asyncHandler(async (req, res) => { const extension = await requireExtensionPrincipal(req, oauth, "browser:observations:write"); const input = z.object({ installationId: z.string().uuid(), candidates: z.array(z.unknown()).min(1).max(3) }).parse(req.body); res.status(201).json({ candidates: await browserAgent.saveCandidates(extension.userId, input.installationId, uuidParam(req.params.id), input.candidates) }); }));
  app.post("/api/v1/browser/tasks/:id/product-proposal", limit(store, "browser_observation", 120, 60), asyncHandler(async (req, res) => { const extension = await requireExtensionPrincipal(req, oauth, "browser:observations:write"); const input = z.object({ installationId: z.string().uuid(), candidateId: z.string().uuid().optional(), candidate: z.unknown().optional(), source: z.enum(["recommended", "manual", "agent"]) }).refine((value) => Boolean(value.candidateId) !== Boolean(value.candidate), "Provide a candidateId or candidate.").parse(req.body); res.status(201).json(await browserAgent.proposeCandidate(uuidParam(req.params.id), extension.userId, input.installationId, input)); }));
  app.post("/api/v1/browser/tasks/:id/product-proposals/:proposalId/confirm", limit(store, "browser_select", 30, 60), asyncHandler(async (req, res) => { const extension = await requireExtensionPrincipal(req, oauth, "browser:tasks:read"); const input = z.object({ installationId: z.string().uuid() }).parse(req.body); res.json({ task: await browserAgent.confirmCandidate(uuidParam(req.params.id), extension.userId, input.installationId, uuidParam(req.params.proposalId)) }); }));
  app.post("/api/v1/browser/tasks/:id/product-proposals/:proposalId/dismiss", limit(store, "browser_select", 30, 60), asyncHandler(async (req, res) => { const extension = await requireExtensionPrincipal(req, oauth, "browser:tasks:read"); const input = z.object({ installationId: z.string().uuid() }).parse(req.body); res.json({ task: await browserAgent.dismissCandidate(uuidParam(req.params.id), extension.userId, input.installationId, uuidParam(req.params.proposalId)) }); }));
  app.post("/api/v1/browser/tasks/:id/site-grant", limit(store, "browser_select", 30, 60), asyncHandler(async (req, res) => { const extension = await requireExtensionPrincipal(req, oauth, "browser:tasks:read"); const input = z.object({ installationId: z.string().uuid(), origin: z.string().url() }).parse(req.body); await browserAgent.recordSiteGrant(uuidParam(req.params.id), extension.userId, input.installationId, input.origin); res.status(201).json({ granted: true }); }));
  app.post("/api/v1/browser/tasks/:id/redacted-page", limit(store, "browser_observation", 120, 60), asyncHandler(async (req, res) => { const extension = await requireExtensionPrincipal(req, oauth, "browser:observations:write"); const input = z.object({ installationId: z.string().uuid(), snapshot: RedactedPageSnapshotSchema }).parse(req.body); res.status(201).json({ snapshot: await browserAgent.saveRedactedPage(uuidParam(req.params.id), extension.userId, input.installationId, input.snapshot) }); }));
  app.get("/api/v1/browser/tasks/:id/operator-command", limit(store, "browser_read", 120, 60), asyncHandler(async (req, res) => { const extension = await requireExtensionPrincipal(req, oauth, "browser:tasks:read"); const installationId = z.string().uuid().parse(req.query.installationId); res.json({ command: await browserAgent.claimOperatorCommand(uuidParam(req.params.id), extension.userId, installationId) }); }));
  app.post("/api/v1/browser/tasks/:id/operator-commands/:commandId/result", limit(store, "browser_observation", 120, 60), asyncHandler(async (req, res) => { const extension = await requireExtensionPrincipal(req, oauth, "browser:observations:write"); const input = z.object({ installationId: z.string().uuid(), status: z.enum(["completed", "blocked", "failed"]), result: z.unknown().optional(), snapshot: RedactedPageSnapshotSchema.optional() }).parse(req.body); await browserAgent.completeOperatorCommand(uuidParam(req.params.id), extension.userId, input.installationId, uuidParam(req.params.commandId), input); res.json({ recorded: true }); }));
  app.post("/api/v1/browser/tasks/:id/payment-preference", limit(store, "browser_select", 30, 60), asyncHandler(async (req, res) => { const extension = await requireExtensionPrincipal(req, oauth, "browser:tasks:read"); const input = z.object({ installationId: z.string().uuid(), paymentPreference: PaymentPreferenceSchema }).parse(req.body); res.json({ task: await browserAgent.setPaymentPreference(uuidParam(req.params.id), extension.userId, input.installationId, input.paymentPreference) }); }));
  app.post("/api/v1/browser/tasks/:id/approval-continuation", limit(store, "browser_execute", 20, 60), asyncHandler(async (req, res) => { const extension = await requireExtensionPrincipal(req, oauth, "browser:execute"); const input = z.object({ installationId: z.string().uuid(), redirectUri: z.string().url(), state: z.string().min(20).max(200) }).parse(req.body); const continuation = await browserAgent.createApprovalContinuation(uuidParam(req.params.id), extension.userId, input.installationId, input); res.status(201).json({ ...continuation, authorizeUrl: `${config.publicBaseUrl}/shopping/${uuidParam(req.params.id)}?continuation=${continuation.continuationId}` }); }));
  app.post("/api/v1/browser/tasks/:id/status", limit(store, "browser_observation", 120, 60), asyncHandler(async (req, res) => { const extension = await requireExtensionPrincipal(req, oauth, "browser:observations:write"); const input = z.object({ installationId: z.string().uuid(), status: z.enum(["searching", "navigating", "checkout_configuring", "payment_choice_required", "payment_action_required", "user_action_required", "failed"]), detail: z.string().max(240).optional() }).parse(req.body); await browserAgent.reportStatus(uuidParam(req.params.id), extension.userId, input.installationId, input.status, input.detail); res.json({ recorded: true }); }));
  app.post("/api/v1/browser/tasks/:id/checkout-observation", limit(store, "browser_observation", 120, 60), asyncHandler(async (req, res) => { const extension = await requireExtensionPrincipal(req, oauth, "browser:observations:write"); const input = z.object({ installationId: z.string().uuid(), observation: z.unknown() }).parse(req.body); res.status(201).json(await browserAgent.observeCheckout(uuidParam(req.params.id), extension.userId, input.installationId, input.observation)); }));
  app.post("/api/v1/browser/tasks/:id/execution-claim", limit(store, "browser_execute", 20, 60), asyncHandler(async (req, res) => { const extension = await requireExtensionPrincipal(req, oauth, "browser:execute"); const input = z.object({ installationId: z.string().uuid(), observation: z.unknown() }).parse(req.body); res.json(await browserAgent.claimExecution(uuidParam(req.params.id), extension.userId, input.installationId, input.observation)); }));
  app.post("/api/v1/browser/tasks/:id/execution-result", limit(store, "browser_execute", 20, 60), asyncHandler(async (req, res) => {
    const extension = await requireExtensionPrincipal(req, oauth, "browser:execute");
    const input = z.object({
      installationId: z.string().uuid(),
      executionGrant: z.string().min(20).max(200),
      status: z.enum(["completed", "user_action_required", "reconciliation_required", "failed"]),
      detail: z.string().max(240).optional(),
    }).parse(req.body);
    res.json(await browserAgent.reportExecution(
      uuidParam(req.params.id),
      extension.userId,
      input.installationId,
      input,
    ));
  }));

  app.get(["/.well-known/oauth-protected-resource", "/.well-known/oauth-protected-resource/mcp"], (_req, res) => res.json(oauth.protectedResourceMetadata()));
  app.get(["/.well-known/oauth-authorization-server", "/.well-known/openid-configuration"], (_req, res) => res.json(oauth.authorizationServerMetadata()));
  app.get("/oauth/authorize", requireBrowserRedirect, asyncHandler(async (req, res) => { const validated = oauth.validateAuthorizationRequest(queryRecord(req)); const csrf = cookie(req, "agentrail_csrf") ?? ""; res.type("html").send(consentPage(validated, csrf, principal(res).user.displayName)); }));
  app.post("/oauth/authorize", express.urlencoded({ extended: false, limit: "32kb" }), requireBrowserRedirect, requireCsrf, asyncHandler(async (req, res) => { const validated = oauth.validateAuthorizationRequest(bodyRecord(req)); res.redirect(303, await oauth.authorize(principal(res).user.id, validated)); }));
  app.post("/oauth/token", express.urlencoded({ extended: false, limit: "32kb" }), limit(store, "oauth_token", 30, 60), asyncHandler(async (req, res) => { const body = bodyRecord(req); if (body.grant_type === "authorization_code") res.json(await oauth.exchangeCode({ code: required(body.code), codeVerifier: required(body.code_verifier), clientId: required(body.client_id), redirectUri: required(body.redirect_uri), resource: required(body.resource) })); else if (body.grant_type === "refresh_token") res.json(await oauth.refresh({ refreshToken: required(body.refresh_token), clientId: required(body.client_id), resource: required(body.resource) })); else throw new SpendSealError(400, "unsupported_grant_type", "Only authorization_code and refresh_token grants are supported."); }));
  app.post("/oauth/revoke", express.urlencoded({ extended: false, limit: "32kb" }), asyncHandler(async (req, res) => { await oauth.revoke(required(bodyRecord(req).token)); res.status(200).end(); }));

  app.post("/mcp", limit(store, "mcp", 120, 60), asyncHandler(async (req, res) => { const token = bearer(req); const principal = token ? await oauth.authenticate(token) : null; if (!principal || principal.resource !== config.publicBaseUrl) { res.setHeader("WWW-Authenticate", `Bearer resource_metadata="${config.publicBaseUrl}/.well-known/oauth-protected-resource", scope="${MCP_SCOPES.join(" ")}"`); res.status(401).json({ error: "invalid_token" }); return; } await handleMcpRequest(service, store, browserAgent, principal, req, res); }));
  app.get("/mcp", (_req, res) => res.status(405).json({ error: "Streamable HTTP accepts POST requests." }));

  const webDist = resolveWebDist(); app.use(express.static(webDist)); app.use((req, res, next) => { if (req.method === "GET" && !req.path.startsWith("/api/") && req.path !== "/mcp" && !req.path.startsWith("/.well-known/") && !req.path.startsWith("/oauth/")) res.sendFile(path.join(webDist, "index.html"), (error) => error ? next() : undefined); else next(); });
  app.use((error: unknown, _req: Request, res: Response, _next: NextFunction) => {
    if (error instanceof z.ZodError) { res.status(400).json({ error: { code: "INVALID_INPUT", message: "Request validation failed.", details: error.flatten() } }); return; }
    if (error instanceof SpendSealError) { res.status(error.status).json({ error: { code: error.code, message: error.message } }); return; }
    if (error instanceof Error && browserErrorStatus(error.message)) {
      res.status(browserErrorStatus(error.message)!).json({ error: { code: error.message, message: browserErrorMessage(error.message) } });
      return;
    }
    console.error(JSON.stringify({ level: "error", event: "request_failed", requestId: res.locals.requestId, message: error instanceof Error ? error.message : "Unknown error" }));
    res.status(500).json({ error: { code: "INTERNAL_ERROR", message: "SpendSeal could not complete the request." } });
  });
  return { app, service, store, browserAgent, webauthn, oauth };
}

async function attachSession(req: Request, res: Response, store: SpendSealStore, config: Config) { const token = cookie(req, "agentrail_session"); if (token) res.locals.principal = await store.getSession(token, config.sessionIdleMinutes); }
function requireBrowser(_req: Request, res: Response, next: NextFunction) { if (!principalOptional(res)) { res.status(401).json({ error: { code: "AUTH_REQUIRED", message: "Sign in with your SpendSeal passkey." } }); return; } next(); }
function requireBrowserRedirect(req: Request, res: Response, next: NextFunction) { if (!principalOptional(res)) { const returnTo = encodeURIComponent(req.originalUrl); res.redirect(303, `/login?returnTo=${returnTo}`); return; } next(); }
function requireCsrf(req: Request, res: Response, next: NextFunction) { const value = String(req.header("x-csrf-token") ?? req.body?.csrf_token ?? ""); const expected = principalOptional(res)?.csrfHash; if (!expected || sha256(value) !== expected) { res.status(403).json({ error: { code: "CSRF_INVALID", message: "The request CSRF token is missing or invalid." } }); return; } next(); }
function requireCsrfIfBrowser(req: Request, res: Response, next: NextFunction) { if (principalOptional(res)) requireCsrf(req, res, next); else next(); }
function requireBrowserOrApiKey(store: SpendSealStore, scope: string) { return asyncHandler(async (req, res, next) => { if (principalOptional(res)) { next(); return; } const token = bearer(req); const supportedPrefix = token?.startsWith("ss_test_") || token?.startsWith("ar_test_"); const key = supportedPrefix ? await store.authenticateApiKey(token!) : null; if (!key || !key.scopes.includes(scope)) throw new SpendSealError(401, "AUTH_REQUIRED", "A merchant session or scoped API key is required."); res.locals.apiKey = key; next(); }); }
async function requireMerchantAccess(res: Response, store: SpendSealStore, merchantId: string, roles: string[]) { const browser = principalOptional(res); if (browser) return requireMembership(store, browser.user.id, merchantId, roles); if (res.locals.apiKey?.merchantId !== merchantId) throw new SpendSealError(403, "TENANT_ACCESS_DENIED", "The API key belongs to another merchant."); }
async function requireMembership(store: SpendSealStore, userId: string, merchantId: string, roles: string[]) { if (!await store.requireMembership(userId, merchantId, roles)) throw new SpendSealError(403, "TENANT_ACCESS_DENIED", "Your merchant role does not permit this operation."); }
async function ownerId(store: SpendSealStore, merchantId: string): Promise<string> { const result = await store.pool.query("SELECT user_id FROM merchant_memberships WHERE merchant_id=$1 AND role='owner' ORDER BY created_at LIMIT 1", [merchantId]); if (!result.rows[0]) throw new SpendSealError(409, "MERCHANT_OWNER_MISSING", "Merchant owner is unavailable."); return result.rows[0].user_id; }
function setSession(res: Response, session: { token: string; csrf: string }, config: Config) { const secure = config.webauthnOrigin.startsWith("https://"); res.cookie("agentrail_session", session.token, { httpOnly: true, secure, sameSite: "lax", maxAge: config.sessionAbsoluteHours * 3600_000, path: "/" }); res.cookie("agentrail_csrf", session.csrf, { httpOnly: false, secure, sameSite: "lax", maxAge: config.sessionAbsoluteHours * 3600_000, path: "/" }); }
function clearSession(res: Response) { res.clearCookie("agentrail_session", { path: "/" }); res.clearCookie("agentrail_csrf", { path: "/" }); }
function principal(res: Response): SessionPrincipal { const value = principalOptional(res); if (!value) throw new SpendSealError(401, "AUTH_REQUIRED", "Authentication required."); return value; }
function principalOptional(res: Response): SessionPrincipal | null { return res.locals.principal ?? null; }
function cookie(req: Request, name: string): string | undefined { return String(req.header("cookie") ?? "").split(";").map((value) => value.trim()).find((value) => value.startsWith(`${name}=`))?.slice(name.length + 1).split("%20").join(" "); }
function approvalCookieName(id: string) { return `agentrail_approval_${id.replaceAll("-", "")}`; }
function requireApprovalCookie(req: Request) { const value = cookie(req, approvalCookieName(String(req.params.id))); if (!value) throw new SpendSealError(403, "APPROVAL_SESSION_INVALID", "Open the original approval link first."); return decodeURIComponent(value); }
function bearer(req: Request): string | null { const header = String(req.header("authorization") ?? ""); return header.startsWith("Bearer ") ? header.slice(7) : null; }
async function requireExtensionPrincipal(req: Request, oauth: OAuthService, scope: typeof BROWSER_SCOPES[number]): Promise<BrowserPrincipal> { const token = bearer(req); const principal = token ? await oauth.authenticate(token, scope) : null; if (!principal || principal.clientId !== oauth.config.extensionOauthClientId || principal.resource !== oauth.config.publicBaseUrl) throw new SpendSealError(401, "AUTH_REQUIRED", `The SpendSeal extension needs ${scope}.`); return { userId: principal.userId, clientId: principal.clientId, scopes: principal.scopes }; }
function uuidParam(value: string | string[] | undefined): string { return z.string().uuid().parse(String(value)); }
function stringQuery(value: unknown): string | undefined { return typeof value === "string" ? value : undefined; }
function numberQuery(value: unknown): number | undefined { return typeof value === "string" ? Number(value) : undefined; }
function productInput() { return z.object({ sku: z.string().min(1).max(80), name: z.string().min(1).max(160), description: z.string().max(2000).default(""), pricePaise: z.number().int().positive().max(100_000_000), refundable: z.boolean(), refundWindowDays: z.number().int().min(0).max(365), active: z.boolean().default(true) }); }
function productUpdateInput() { return z.object({ expectedVersion: z.number().int().positive(), changes: productInput().partial().refine((value) => Object.keys(value).length > 0, "At least one product field must change") }); }
function limit(store: SpendSealStore, bucket: string, count: number, seconds: number) { return asyncHandler(async (req, res, next) => { const authorization = bearer(req); const subject = principalOptional(res)?.user.id ?? (authorization ? `token:${sha256(authorization).slice(0, 20)}` : req.ip ?? "unknown"); if (!await store.rateLimit(`${bucket}:${subject}`, count, seconds)) throw new SpendSealError(429, "RATE_LIMITED", "Too many requests. Try again later."); next(); }); }
function asyncHandler(handler: (req: Request, res: Response, next: NextFunction) => Promise<unknown>) { return (req: Request, res: Response, next: NextFunction) => { void handler(req, res, next).catch(next); }; }
function queryRecord(req: Request): Record<string, string | undefined> { return Object.fromEntries(Object.entries(req.query).map(([key, value]) => [key, typeof value === "string" ? value : undefined])); }
function bodyRecord(req: Request): Record<string, string | undefined> { return Object.fromEntries(Object.entries(req.body ?? {}).map(([key, value]) => [key, typeof value === "string" ? value : undefined])); }
function required(value: string | undefined): string { if (!value) throw new SpendSealError(400, "invalid_request", "A required OAuth parameter is missing."); return value; }
function consentPage(input: { clientId: string; redirectUri: string; resource: string; codeChallenge: string; scopes: string[]; state: string }, csrf: string, displayName: string) {
  const extension = input.clientId === "spendseal-browser-extension";
  const clientName = extension ? "SpendSeal browser extension" : "ChatGPT";
  const limitation = extension
    ? "The extension can observe only supported shopping pages. It cannot read passwords, raw card details, cookies, or browsing history."
    : "ChatGPT cannot select the final listing, approve a Purchase Seal, or execute an order.";
  const hidden = { response_type: "code", client_id: input.clientId, redirect_uri: input.redirectUri, resource: input.resource, code_challenge: input.codeChallenge, code_challenge_method: "S256", scope: input.scopes.join(" "), state: input.state, csrf_token: csrf };
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Authorize SpendSeal</title><style>body{font-family:system-ui;background:#07110e;color:#eefbf5;display:grid;place-items:center;min-height:100vh;margin:0}.card{max-width:560px;padding:32px;border:1px solid #315347;border-radius:24px;background:#0b1814}button{padding:14px 20px;border:0;border-radius:12px;background:#78f0c1;color:#06110d;font-weight:700;width:100%}code{color:#78f0c1}li{margin:8px 0}</style></head><body><main class="card"><h1>Connect ${escapeHtml(clientName)} to SpendSeal</h1><p>Signed in as <strong>${escapeHtml(displayName)}</strong>. ${escapeHtml(clientName)} requests these buyer permissions:</p><ul>${input.scopes.map((scope) => `<li><code>${escapeHtml(scope)}</code></li>`).join("")}</ul><p>${escapeHtml(limitation)}</p><form method="post" action="/oauth/authorize">${Object.entries(hidden).map(([key, value]) => `<input type="hidden" name="${key}" value="${escapeHtml(value)}">`).join("")}<button type="submit">Authorize connection</button></form></main></body></html>`;
}

function browserErrorStatus(code: string): number | null {
  if (code === "BROWSER_AGENT_DISABLED") return 404;
  if (["SHOPPING_TASK_NOT_FOUND", "CANDIDATE_NOT_FOUND"].includes(code)) return 404;
  if (["INSTALLATION_NOT_AUTHORIZED", "EXECUTION_GRANT_INVALID", "APPROVAL_REDIRECT_INVALID"].includes(code)) return 403;
  if (["TASK_STATE_INVALID", "CONFIRMATION_REQUIRED", "CANDIDATE_COUNT_INVALID", "DOMAIN_MISMATCH", "APPROVAL_CONTINUATION_INVALID"].includes(code)) return 409;
  return null;
}
function browserErrorMessage(code: string): string {
  const messages: Record<string, string> = {
    BROWSER_AGENT_DISABLED: "Browser purchasing is disabled on this SpendSeal deployment.",
    SHOPPING_TASK_NOT_FOUND: "This Shopping Task was not found for the signed-in buyer.",
    CANDIDATE_NOT_FOUND: "The selected product candidate is no longer available.",
    INSTALLATION_NOT_AUTHORIZED: "This browser extension installation is not authorized for the buyer.",
    EXECUTION_GRANT_INVALID: "The execution grant is invalid, expired, or already used.",
    TASK_STATE_INVALID: "The Shopping Task is not ready for that action.",
    CONFIRMATION_REQUIRED: "Approve the exact Purchase Seal with your passkey first.",
    CANDIDATE_COUNT_INVALID: "SpendSeal accepts between one and three candidates.",
    DOMAIN_MISMATCH: "The observed page does not belong to the Shopping Task's exact approved site.",
    APPROVAL_REDIRECT_INVALID: "The approval return address does not belong to this Chromium extension.",
    APPROVAL_CONTINUATION_INVALID: "The automatic approval return expired or was already used.",
  };
  return messages[code] ?? "SpendSeal refused the browser action.";
}
function escapeHtml(value: string) { return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!); }
function resolveWebDist(): string { const candidates = [path.resolve(process.cwd(), "apps/web/dist"), path.resolve(process.cwd(), "../web/dist")]; return candidates.find((candidate) => path.isAbsolute(candidate) && candidate && requireDirectory(candidate)) ?? candidates[0]!; }
function requireDirectory(candidate: string): boolean { try { return fs.statSync(candidate).isDirectory(); } catch { return false; } }
