declare const chrome: any;
const API = "https://spendseal.vercel.app";
const CLIENT_ID = "spendseal-browser-extension";
const SCOPES = ["browser:tasks:read", "browser:observations:write", "browser:execute"];
chrome.runtime.onInstalled.addListener(() => chrome.sidePanel.setPanelBehavior({ openPanelOnActionClick: true }));
chrome.runtime.onMessage.addListener((message: any, _sender: any, respond: (value: any) => void) => { void handle(message).then(respond).catch((error) => respond({ error: error instanceof Error ? error.message : "Extension request failed" })); return true; });

async function handle(message: any) {
  if (message.type === "connect") return connect();
  if (message.type === "state") return state();
  if (message.type === "pending") return api("/api/v1/browser/tasks/pending");
  if (message.type === "openTask") return openTask(message.task);
  if (message.type === "inspect") return inspect(message.taskId);
  if (message.type === "select") return select(message.taskId, message.candidateId, message.productUrl);
  if (message.type === "buyNow") return commandActive("buyNow");
  if (message.type === "revalidate") return revalidate(message.taskId);
  if (message.type === "finalize") return finalize(message.taskId);
  if (message.type === "disconnect") { await disconnect(); return { connected: false }; }
  throw new Error("Unknown extension command");
}
async function connect() {
  const verifier = base64url(crypto.getRandomValues(new Uint8Array(48))); const challenge = base64url(new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(verifier))));
  const redirectUri = chrome.identity.getRedirectURL("oauth2"); const stateValue = crypto.randomUUID(); const url = new URL(`${API}/oauth/authorize`);
  Object.entries({ response_type: "code", client_id: CLIENT_ID, redirect_uri: redirectUri, resource: API, code_challenge: challenge, code_challenge_method: "S256", scope: SCOPES.join(" "), state: stateValue }).forEach(([key, value]) => url.searchParams.set(key, value));
  const callback = await chrome.identity.launchWebAuthFlow({ url: url.toString(), interactive: true }); if (!callback) throw new Error("SpendSeal authorization was cancelled.");
  const returned = new URL(callback); if (returned.searchParams.get("state") !== stateValue) throw new Error("OAuth state did not match.");
  const response = await fetch(`${API}/oauth/token`, { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ grant_type: "authorization_code", code: returned.searchParams.get("code") ?? "", code_verifier: verifier, client_id: CLIENT_ID, redirect_uri: redirectUri, resource: API }) });
  if (!response.ok) throw new Error("SpendSeal token exchange failed."); const tokens = await response.json(); let { installationId } = await chrome.storage.local.get(["installationId"]); installationId ||= crypto.randomUUID(); await chrome.storage.local.set({ tokens, installationId });
  const registration = await api("/api/v1/browser/installations", { method: "POST", body: JSON.stringify({ installationId, name: "Local Chromium extension" }) });
  await chrome.storage.local.set({ livePurchaseEnabled: registration.livePurchaseEnabled === true });
  return { connected: true, installationId };
}
async function state() { const stored = await chrome.storage.local.get(["tokens", "installationId", "activeTaskId", "livePurchaseEnabled"]); return { connected: Boolean(stored.tokens), installationId: stored.installationId ?? null, activeTaskId: stored.activeTaskId ?? null, livePurchaseEnabled: stored.livePurchaseEnabled === true }; }
async function openTask(task: any) { await chrome.storage.local.set({ activeTaskId: task.id }); await report(task.id, task.productUrl ? "navigating" : "searching"); const target = task.productUrl ?? (task.site === "amazon_in" ? `https://www.amazon.in/s?k=${encodeURIComponent(task.query)}` : `https://www.flipkart.com/search?q=${encodeURIComponent(task.query)}`); await chrome.tabs.create({ url: target, active: true }); return { opened: target }; }
async function inspect(taskId: string) { const details = await api(`/api/v1/browser/tasks/${taskId}`); const observed = await commandActive("inspect", { site: details.task.site }); if (observed.error) throw new Error(observed.error); if (observed.userActionRequired) { await report(taskId, "user_action_required", observed.reason); return observed; } if (observed.kind === "candidates") return api(`/api/v1/browser/tasks/${taskId}/candidates`, { method: "POST", body: JSON.stringify({ installationId: await installationId(), candidates: observed.candidates }) }); if (observed.kind === "checkout") return api(`/api/v1/browser/tasks/${taskId}/checkout-observation`, { method: "POST", body: JSON.stringify({ installationId: await installationId(), observation: observed.observation }) }); throw new Error(observed.reason ?? "SpendSeal could not confidently inspect this page."); }
async function select(taskId: string, candidateId: string, productUrl: string) { const result = await api(`/api/v1/browser/tasks/${taskId}/select`, { method: "POST", body: JSON.stringify({ candidateId }) }); await chrome.tabs.update(await activeTabId(), { url: productUrl, active: true }); return result; }
async function revalidate(taskId: string) { const observed = await commandActive("inspect"); if (observed.kind !== "checkout") throw new Error("Open the final checkout page before revalidation."); const claim = await api(`/api/v1/browser/tasks/${taskId}/execution-claim`, { method: "POST", body: JSON.stringify({ installationId: await installationId(), observation: observed.observation }) }); if (claim.status !== "submitting") return claim; const livePurchaseEnabled = (await chrome.storage.local.get(["livePurchaseEnabled"])).livePurchaseEnabled === true; const submission = await commandActive("submitLive", { livePurchaseEnabled, executionGrant: claim.executionGrant }); if (!submission.submitted) return reportExecution(taskId, claim.executionGrant, "failed", submission.reason); await chrome.storage.local.set({ executionGrant: claim.executionGrant }); return { ...claim, submissionStarted: true }; }
async function finalize(taskId: string) { const executionGrant = (await chrome.storage.local.get(["executionGrant"])).executionGrant; if (!executionGrant) throw new Error("No active execution grant."); const outcome = await commandActive("executionOutcome"); const result = await reportExecution(taskId, executionGrant, outcome.status, outcome.detail); await chrome.storage.local.remove("executionGrant"); return result; }
async function reportExecution(taskId: string, executionGrant: string, status: string, detail?: string) { return api(`/api/v1/browser/tasks/${taskId}/execution-result`, { method: "POST", body: JSON.stringify({ installationId: await installationId(), executionGrant, status, detail }) }); }
async function disconnect() { const stored = await chrome.storage.local.get(["tokens", "installationId"]); if (stored.installationId && stored.tokens) await api(`/api/v1/browser/installations/${stored.installationId}`, { method: "DELETE" }).catch(() => undefined); if (stored.tokens?.refresh_token) await fetch(`${API}/oauth/revoke`, { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ token: stored.tokens.refresh_token }) }).catch(() => undefined); await chrome.storage.local.clear(); }
async function report(taskId: string, status: string, detail?: string) { return api(`/api/v1/browser/tasks/${taskId}/status`, { method: "POST", body: JSON.stringify({ installationId: await installationId(), status, detail }) }); }
async function api(path: string, init: RequestInit = {}) { let tokens = (await chrome.storage.local.get(["tokens"])).tokens; if (!tokens) throw new Error("Connect the extension first."); let response = await fetch(`${API}${path}`, { ...init, headers: { "content-type": "application/json", authorization: `Bearer ${tokens.access_token}`, ...(init.headers ?? {}) } }); if (response.status === 401 && tokens.refresh_token) { tokens = await refresh(tokens.refresh_token); response = await fetch(`${API}${path}`, { ...init, headers: { "content-type": "application/json", authorization: `Bearer ${tokens.access_token}`, ...(init.headers ?? {}) } }); } const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error?.message ?? data.error?.code ?? `SpendSeal returned ${response.status}`); return data; }
async function refresh(refreshToken: string) { const response = await fetch(`${API}/oauth/token`, { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ grant_type: "refresh_token", refresh_token: refreshToken, client_id: CLIENT_ID, resource: API }) }); if (!response.ok) { await chrome.storage.local.remove("tokens"); throw new Error("Reconnect the extension."); } const tokens = await response.json(); await chrome.storage.local.set({ tokens }); return tokens; }
async function commandActive(action: string, extra: any = {}) { const tabId = await activeTabId(); try { return await chrome.tabs.sendMessage(tabId, { action, ...extra }); } catch { await chrome.scripting.executeScript({ target: { tabId }, files: ["content.js"] }); return chrome.tabs.sendMessage(tabId, { action, ...extra }); } }
async function activeTabId() { const [tab] = await chrome.tabs.query({ active: true, currentWindow: true }); if (!tab?.id) throw new Error("No active shopping tab."); return tab.id; }
async function installationId() { const value = (await chrome.storage.local.get(["installationId"])).installationId; if (!value) throw new Error("Extension is not registered."); return value; }
function base64url(bytes: Uint8Array) { let binary = ""; bytes.forEach((byte) => binary += String.fromCharCode(byte)); return btoa(binary).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", ""); }
